### ISSUE TITLE
No Image received

### ISSUE THREAD

**Issue by tianyaoZhang** [uzh-rpg/sim2real_drone_racing#12]
Environment:
- Ubuntu 18.04
- ROS Melodic
- OpenCV 3.4.11
- python 2.7
- TensorFlow 1.13.1

Problem:
I have followed the Step-by-Step Procedure, and built the environment successfully. However, when I start racing, what I got is shown as follow:

![image](https://user-images.githubusercontent.com/33508407/91718650-5fb57180-ebc6-11ea-88c7-bbd390bcb1be.png)

I noticed three Error information:

(1)
> Traceback (most recent call last):
>   File "/home/tyZhang/Documents/tyZhang/RPG/drone_racing_ws/catkin_ddr/src/sim2real_drone_racing/learning/deep_drone_racing_learning_node/nodes/deep_drone_racing_node.py", line 31, in <module>
>     run_network()
>   File "/home/tyZhang/Documents/tyZhang/RPG/drone_racing_ws/catkin_ddr/src/sim2real_drone_racing/learning/deep_drone_racing_learning_node/nodes/deep_drone_racing_node.py", line 19, in run_network
>     network.run(sess)
>   File "/home/tyZhang/Documents/tyZhang/RPG/drone_racing_ws/catkin_ddr/src/sim2real_drone_racing/learning/deep_drone_racing_learning_node/src/Network/Network.py", line 82, in run
>     cv_input_image = bridge.imgmsg_to_cv2(data_camera)
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/cv_bridge/core.py", line 163, in imgmsg_to_cv2
>     dtype, n_channels = self.encoding_to_dtype_with_channels(img_msg.encoding)
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/cv_bridge/core.py", line 99, in encoding_to_dtype_with_channels
>     return self.cvtype2_to_dtype_with_channels(self.encoding_to_cvtype2(encoding))
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/cv_bridge/core.py", line 91, in encoding_to_cvtype2
>     from cv_bridge.boost.cv_bridge_boost import getCvType
> ImportError: libopencv_core.so.3.2: cannot open shared object file: No such file or directory
> 

(2)

> ERROR: cannot launch node of type [joy/joy_node]: joy
> ROS path [0]=/opt/ros/melodic/share/ros
> .....

(3)

> process[hummingbird/drone_racing_node-10]: started with pid [25991]
> /home/tyZhang/Documents/tyZhang/RPG/drone_racing_ws/catkin_ddr/devel/lib/drone_racing/drone_racing_node: error while loading shared libraries: libopencv_imgcodecs.so.3.2: cannot open shared object file: No such file or directory
> [hummingbird/drone_racing_node-10] process has died [pid 25991, exit code 127, cmd /home/tyZhang/Documents/tyZhang/RPG/drone_racing_ws/catkin_ddr/devel/lib/drone_racing/drone_racing_node image_rgb:=/hummingbird/rgb_camera/camera_1/image_raw camera_info:=/hummingbird/vi_sensor_1/camera_depth/depth/camera_info state_estimate:=odometry_sensor1/odometry __name:=drone_racing_node __log:=/home/tyZhang/.ros/log/0e72b08c-eb83-11ea-a3da-3497f6dc6705/hummingbird-drone_racing_node-10.log].
> 

What should I do next? Thanks.

**Comment by antonilo** [comment]
You probably have a conflict between the opencv installed globally (Version 3.4) and the local opencv_bridge (Version 3.2). I would recommend downgrading opencv to 3.2

**Comment by raghada** [comment]
Same here, did you manage to solve it?

**Comment by raghada** [comment]
I'm using opencv 3.2 and I'm having the same issue
