### ISSUE TITLE
roslaunch failed

### ISSUE THREAD

**Issue by QuantumY-CHN** [uzh-rpg/sim2real_drone_racing#14]
Thank you for your fantastic work.

I'm in Ubuntu 18.04, ROS Melodic. But got some problems while launching net controller within the virtualenv 'droneflow'. Could you please give me some advice? Thanks in advance. 

```
(droneflow) ubuntu@dbfb2a9cb529:~/catkin_wss/drone_racing_ws$ roslaunch deep_drone_racing_learning  net_controller_launch.launch
... logging to /home/ubuntu/.ros/log/9d640d72-67ff-11ed-bfdc-0242ac110002/roslaunch-dbfb2a9cb529-167807.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://dbfb2a9cb529:39213/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.13

NODES
  /
    deep_drone_racing_learning (deep_drone_racing_learning/deep_drone_racing_node.py)

auto-starting new master
process[master]: started with pid [167817]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 9d640d72-67ff-11ed-bfdc-0242ac110002
process[rosout-1]: started with pid [167828]
started core service [/rosout]
process[deep_drone_racing_learning-2]: started with pid [167831]
Traceback (most recent call last):
  File "/home/ubuntu/catkin_wss/drone_racing_ws/catkin_ddr/src/sim2real_drone_racing/learning/deep_drone_racing_learning_node/nodes/deep_drone_racing_node.py", line 4, in <module>
    from Network import Network
  File "/home/ubuntu/catkin_wss/drone_racing_ws/catkin_ddr/src/sim2real_drone_racing/learning/deep_drone_racing_learning_node/src/Network/Network.py", line 13, in <module>
    from ddr_learner.models.base_learner import TrajectoryLearner
  File "/home/ubuntu/catkin_wss/drone_racing_ws/catkin_ddr/src/sim2real_drone_racing/learning/deep_drone_racing_learner/src/ddr_learner/models/base_learner.py", line 10, in <module>
    from keras.utils.generic_utils import Progbar
  File "/home/ubuntu/catkin_wss/drone_racing_ws/droneflow/local/lib/python2.7/site-packages/keras/__init__.py", line 20, in <module>
    from keras import distribute
  File "/home/ubuntu/catkin_wss/drone_racing_ws/droneflow/local/lib/python2.7/site-packages/keras/distribute/__init__.py", line 18, in <module>
    from keras.distribute import sidecar_evaluator
  File "/home/ubuntu/catkin_wss/drone_racing_ws/droneflow/local/lib/python2.7/site-packages/keras/distribute/sidecar_evaluator.py", line 195
    f"{_CHECKPOINT_TIMEOUT_SEC} seconds. "
    ^
SyntaxError: invalid syntax
[deep_drone_racing_learning-2] process has died [pid 167831, exit code 1, cmd /home/ubuntu/catkin_wss/drone_racing_ws/catkin_ddr/src/sim2real_drone_racing/learning/deep_drone_racing_learning_node/nodes/deep_drone_racing_node.py --f=0.5 --ckpt_file=/home/ubuntu/catkin_wss/drone_racing_ws/catkin_ddr/src/sim2real_drone_racing/learning/deep_drone_racing_learner/src/ddr_learner/results/best_model/navigation_model cnn_predictions:=/cnn_out/traj state_change:=/hummingbird/state_change camera:=/hummingbird/rgb_camera/camera_1/image_raw state_estimate:=/hummingbird/state_estimate __name:=deep_drone_racing_learning __log:=/home/ubuntu/.ros/log/9d640d72-67ff-11ed-bfdc-0242ac110002/deep_drone_racing_learning-2.log].
log file: /home/ubuntu/.ros/log/9d640d72-67ff-11ed-bfdc-0242ac110002/deep_drone_racing_learning-2*.log
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```

**Comment by QuantumY-CHN** [comment]
There are several similar errors here since that python version < 3.6. I manually removed 'f's. Then the error became

```
Traceback (most recent call last):
  File "/home/ubuntu/catkin_wss/drone_racing_ws/catkin_ddr/src/sim2real_drone_racing/learning/deep_drone_racing_learning_node/nodes/deep_drone_racing_node.py", line 4, in <module>
    from Network import Network
  File "/home/ubuntu/catkin_wss/drone_racing_ws/catkin_ddr/src/sim2real_drone_racing/learning/deep_drone_racing_learning_node/src/Network/Network.py", line 13, in <module>
    from ddr_learner.models.base_learner import TrajectoryLearner
  File "/home/ubuntu/catkin_wss/drone_racing_ws/catkin_ddr/src/sim2real_drone_racing/learning/deep_drone_racing_learner/src/ddr_learner/models/base_learner.py", line 10, in <module>
    from keras.utils.generic_utils import Progbar
  File "/home/ubuntu/catkin_wss/drone_racing_ws/droneflow/local/lib/python2.7/site-packages/keras/__init__.py", line 20, in <module>
    from keras import distribute
  File "/home/ubuntu/catkin_wss/drone_racing_ws/droneflow/local/lib/python2.7/site-packages/keras/distribute/__init__.py", line 18, in <module>
    from keras.distribute import sidecar_evaluator
  File "/home/ubuntu/catkin_wss/drone_racing_ws/droneflow/local/lib/python2.7/site-packages/keras/distribute/sidecar_evaluator.py", line 17, in <module>
    import tensorflow.compat.v2 as tf
ImportError: No module named v2
[deep_drone_racing_learning-2] process has died [pid 173880, exit code 1, cmd /home/ubuntu/catkin_wss/drone_racing_ws/catkin_ddr/src/sim2real_drone_racing/learning/deep_drone_racing_learning_node/nodes/deep_drone_racing_node.py --f=0.5 --ckpt_file=/home/ubuntu/catkin_wss/drone_racing_ws/catkin_ddr/src/sim2real_drone_racing/learning/deep_drone_racing_learner/src/ddr_learner/results/best_model/navigation_model cnn_predictions:=/cnn_out/traj state_change:=/hummingbird/state_change camera:=/hummingbird/rgb_camera/camera_1/image_raw state_estimate:=/hummingbird/state_estimate __name:=deep_drone_racing_learning __log:=/home/ubuntu/.ros/log/577e6ef2-6812-11ed-9d81-0242ac110002/deep_drone_racing_learning-2.log].
log file: /home/ubuntu/.ros/log/577e6ef2-6812-11ed-9d81-0242ac110002/deep_drone_racing_learning-2*.log

```

I can understand that compat.v2 module was added in tf1.14
But the suggested tf version is 1.13.1 and python 2.7, could you please suggest how can I get across these version conflicts? Many thanks.

**Comment by yabanbingliang** [comment]
Hello.Do you know how to configure the version？
